import "/public/fonts/font-icons.css";
import "@/styles/css/swiper-bundle.min.css";
import "@/styles/scss/app.scss";
import { Inter, Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--poppins",
  display: "swap",
});
const inter = Inter({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--inter",
  display: "swap",
});

export const metadata = {
  title: "Nulivo - Next.js Template",
  description: "Generated by create next app",
  icons: {
    icon: ["/images/favicon.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable}`}>{children}</body>
    </html>
  );
}
